EXAM_CONTENT = {
    "UPSC": {
        "name": "UPSC Civil Services",
        "description": "Prepare for India's most prestigious civil services examination",
        "color": "indigo",
        "subjects": {
            "History": [
                "Ancient India",
                "Medieval India",
                "Modern India",
                "World History",
                "Post-Independence India",
            ],
            "Geography": [
                "Physical Geography",
                "Indian Geography",
                "World Geography",
                "Economic Geography",
                "Environmental Geography",
            ],
            "Polity": [
                "Constitutional Framework",
                "Parliament & State Legislature",
                "Executive & Judiciary",
                "Local Government",
                "Constitutional Bodies",
                "Rights & Duties",
            ],
            "Economy": [
                "Indian Economy Overview",
                "Economic Planning",
                "Agriculture",
                "Industry & Trade",
                "Monetary & Fiscal Policy",
                "Budget & Taxation",
                "International Trade",
            ],
            "Environment": [
                "Ecology & Ecosystem",
                "Biodiversity",
                "Climate Change",
                "Environmental Laws",
                "Conservation",
            ],
            "Science & Technology": [
                "Space Technology",
                "Defence Technology",
                "Biotechnology",
                "IT & Computers",
                "Energy Technologies",
            ],
            "Current Affairs": [
                "National Affairs",
                "International Relations",
                "Government Schemes",
                "Awards & Recognition",
                "Sports",
            ],
        },
    },
    "JEE": {
        "name": "JEE (Joint Entrance Examination)",
        "description": "Crack IIT JEE with comprehensive preparation",
        "color": "blue",
        "subjects": {
            "Physics": [
                "Mechanics",
                "Kinematics",
                "Laws of Motion",
                "Work, Energy & Power",
                "Rotational Motion",
                "Gravitation",
                "Thermodynamics",
                "Waves & Oscillations",
                "Electrostatics",
                "Current Electricity",
                "Magnetic Effects",
                "Electromagnetic Induction",
                "Optics",
                "Modern Physics",
            ],
            "Chemistry": [
                "Some Basic Concepts",
                "Atomic Structure",
                "Chemical Bonding",
                "Equilibrium",
                "Redox Reactions",
                "Electrochemistry",
                "Chemical Kinetics",
                "Organic Chemistry Basics",
                "Hydrocarbons",
                "Alcohols & Ethers",
                "Carbonyl Compounds",
                "Coordination Compounds",
                "p-Block Elements",
                "d & f Block Elements",
            ],
            "Mathematics": [
                "Sets & Relations",
                "Complex Numbers",
                "Quadratic Equations",
                "Sequences & Series",
                "Binomial Theorem",
                "Straight Lines",
                "Circles & Conics",
                "Vectors",
                "3D Geometry",
                "Limits & Continuity",
                "Differentiation",
                "Integration",
                "Differential Equations",
                "Probability & Statistics",
                "Matrices & Determinants",
            ],
        },
    },
    "NEET": {
        "name": "NEET (National Eligibility cum Entrance Test)",
        "description": "Prepare for MBBS/BDS admissions across India",
        "color": "green",
        "subjects": {
            "Physics": [
                "Physical World & Measurement",
                "Kinematics",
                "Laws of Motion",
                "Work, Energy & Power",
                "Rotational Motion",
                "Gravitation",
                "Properties of Matter",
                "Thermodynamics",
                "Kinetic Theory of Gases",
                "Oscillations & Waves",
                "Electrostatics",
                "Current Electricity",
                "Magnetic Effects",
                "Optics",
                "Dual Nature of Matter",
                "Atoms & Nuclei",
                "Electronic Devices",
            ],
            "Chemistry": [
                "Basic Concepts",
                "Atomic Structure",
                "Chemical Bonding",
                "States of Matter",
                "Thermodynamics",
                "Equilibrium",
                "Redox Reactions",
                "Hydrogen & s-Block",
                "p-Block Elements",
                "Organic Chemistry Basics",
                "Hydrocarbons",
                "Environmental Chemistry",
                "Biomolecules",
                "Polymers & Chemistry in Everyday Life",
            ],
            "Biology": [
                "Cell: Structure & Function",
                "Cell Division",
                "Biomolecules",
                "Plant Kingdom",
                "Animal Kingdom",
                "Morphology of Plants",
                "Anatomy of Plants",
                "Structural Organisation in Animals",
                "Digestion & Absorption",
                "Breathing & Gas Exchange",
                "Body Fluids & Circulation",
                "Excretory Products",
                "Locomotion & Movement",
                "Neural Control",
                "Chemical Coordination",
                "Reproduction in Plants",
                "Human Reproduction",
                "Genetics & Evolution",
                "Human Health & Disease",
                "Microbes in Human Welfare",
                "Biotechnology",
                "Ecology",
            ],
        },
    },
}

DIFFICULTY_LABELS = {
    1: "Beginner",
    2: "Easy",
    3: "Medium",
    4: "Hard",
    5: "Expert",
}
