EXAM_CONTENT = {
    # ── NATIONAL EXAMS ────────────────────────────────────────────────
    "UPSC": {
        "name": "UPSC Civil Services",
        "short": "UPSC",
        "description": "India's most prestigious civil services exam",
        "level": "national",
        "state": None,
        "languages": ["english", "hindi"],
        "color": "indigo",
        "subjects": {
            "History": ["Ancient India", "Medieval India", "Modern India", "World History", "Post-Independence India"],
            "Geography": ["Physical Geography", "Indian Geography", "World Geography", "Economic Geography", "Environmental Geography"],
            "Polity": ["Constitutional Framework", "Parliament & State Legislature", "Executive & Judiciary", "Local Government", "Constitutional Bodies", "Rights & Duties"],
            "Economy": ["Indian Economy Overview", "Economic Planning", "Agriculture", "Industry & Trade", "Monetary & Fiscal Policy", "Budget & Taxation", "International Trade"],
            "Environment": ["Ecology & Ecosystem", "Biodiversity", "Climate Change", "Environmental Laws", "Conservation"],
            "Science & Technology": ["Space Technology", "Defence Technology", "Biotechnology", "IT & Computers", "Energy Technologies"],
            "Current Affairs": ["National Affairs", "International Relations", "Government Schemes", "Awards & Recognition", "Sports"],
        },
    },
    "JEE": {
        "name": "JEE (Joint Entrance Examination)",
        "short": "JEE",
        "description": "IIT and NIT engineering entrance exam",
        "level": "national",
        "state": None,
        "languages": ["english", "hindi"],
        "color": "blue",
        "subjects": {
            "Physics": ["Kinematics", "Laws of Motion", "Work Energy Power", "Rotational Motion", "Gravitation", "Thermodynamics", "Waves & Oscillations", "Electrostatics", "Current Electricity", "Magnetic Effects", "Electromagnetic Induction", "Optics", "Modern Physics"],
            "Chemistry": ["Atomic Structure", "Chemical Bonding", "Equilibrium", "Electrochemistry", "Chemical Kinetics", "Organic Chemistry Basics", "Hydrocarbons", "Alcohols & Ethers", "Carbonyl Compounds", "Coordination Compounds", "p-Block Elements", "d & f Block Elements"],
            "Mathematics": ["Complex Numbers", "Quadratic Equations", "Sequences & Series", "Binomial Theorem", "Straight Lines", "Circles & Conics", "Vectors", "3D Geometry", "Limits & Continuity", "Differentiation", "Integration", "Differential Equations", "Probability & Statistics", "Matrices & Determinants"],
        },
    },
    "NEET": {
        "name": "NEET (Medical Entrance)",
        "short": "NEET",
        "description": "MBBS/BDS admission across India",
        "level": "national",
        "state": None,
        "languages": ["english", "hindi", "tamil"],
        "color": "green",
        "subjects": {
            "Physics": ["Kinematics", "Laws of Motion", "Work Energy Power", "Thermodynamics", "Electrostatics", "Current Electricity", "Optics", "Modern Physics", "Electronic Devices"],
            "Chemistry": ["Atomic Structure", "Chemical Bonding", "Thermodynamics", "Equilibrium", "Organic Chemistry Basics", "Hydrocarbons", "Biomolecules", "Polymers"],
            "Biology": ["Cell Structure & Function", "Cell Division", "Plant Kingdom", "Animal Kingdom", "Morphology of Plants", "Human Physiology", "Digestion & Absorption", "Respiration", "Circulation", "Excretion", "Reproduction in Plants", "Human Reproduction", "Genetics & Evolution", "Human Health & Disease", "Biotechnology", "Ecology"],
        },
    },
    "SSC_CGL": {
        "name": "SSC CGL",
        "short": "SSC CGL",
        "description": "Staff Selection Commission - Combined Graduate Level",
        "level": "national",
        "state": None,
        "languages": ["english", "hindi"],
        "color": "orange",
        "subjects": {
            "General Intelligence": ["Analogies", "Classification", "Series", "Coding-Decoding", "Blood Relations", "Direction Sense", "Syllogism", "Puzzles"],
            "General Awareness": ["History", "Geography", "Polity", "Economy", "Science", "Current Affairs", "Static GK"],
            "Quantitative Aptitude": ["Number System", "Percentage", "Ratio & Proportion", "Average", "Profit & Loss", "Time & Work", "Speed Distance Time", "Data Interpretation", "Geometry", "Trigonometry"],
            "English Comprehension": ["Reading Comprehension", "Fill in the Blanks", "Sentence Correction", "Synonyms & Antonyms", "Idioms & Phrases", "One Word Substitution"],
        },
    },
    "IBPS_PO": {
        "name": "IBPS PO",
        "short": "IBPS PO",
        "description": "Bank Probationary Officer entrance exam",
        "level": "national",
        "state": None,
        "languages": ["english", "hindi"],
        "color": "purple",
        "subjects": {
            "Reasoning Ability": ["Syllogism", "Coding-Decoding", "Blood Relations", "Direction Sense", "Seating Arrangement", "Puzzles", "Input-Output", "Inequality"],
            "Quantitative Aptitude": ["Number Series", "Data Interpretation", "Quadratic Equations", "Approximation", "Percentage", "Ratio & Proportion", "Time & Work", "Profit & Loss"],
            "English Language": ["Reading Comprehension", "Cloze Test", "Para Jumbles", "Error Spotting", "Fill in the Blanks", "Sentence Improvement"],
            "General Awareness": ["Banking Awareness", "Financial Awareness", "Current Affairs", "Static GK"],
        },
    },

    # ── TAMIL NADU STATE EXAMS ────────────────────────────────────────
    "TNPSC_GROUP1": {
        "name": "TNPSC Group 1",
        "short": "TNPSC-I",
        "description": "Tamil Nadu's top civil services (Deputy Collector, DSP)",
        "level": "state",
        "state": "Tamil Nadu",
        "languages": ["tamil", "english"],
        "color": "rose",
        "subjects": {
            "General Science": ["Physics Basics", "Chemistry Basics", "Biology Basics", "Science in Daily Life", "Health & Nutrition"],
            "Current Events": ["Tamil Nadu Current Affairs", "National Current Affairs", "International Current Affairs", "Government Schemes"],
            "Geography": ["Tamil Nadu Geography", "Indian Geography", "World Geography", "Natural Calamities"],
            "History & Culture": ["Tamil Nadu History", "Sangam Age", "Medieval Tamil Nadu", "Modern Tamil Nadu", "Indian Freedom Movement", "Tamil Culture & Literature"],
            "Indian Polity": ["Indian Constitution", "Tamil Nadu Government", "Local Administration", "Panchayati Raj", "Human Rights"],
            "Indian Economy": ["Indian Economy Basics", "Tamil Nadu Economy", "Agriculture in TN", "Industrial Policy", "Five Year Plans"],
            "Indian National Movement": ["Early Nationalist Movement", "Gandhian Era", "Revolutionary Movements", "Tamil Nadu's Role in Freedom Struggle"],
            "Aptitude & Mental Ability": ["Simplification", "Percentage", "Ratio & Proportion", "Time & Work", "Number Series", "Logical Reasoning", "Data Interpretation"],
        },
    },
    "TNPSC_GROUP2": {
        "name": "TNPSC Group 2 / 2A",
        "short": "TNPSC-II",
        "description": "Junior Assistant, Revenue Inspector, DEO (Tamil Nadu)",
        "level": "state",
        "state": "Tamil Nadu",
        "languages": ["tamil", "english"],
        "color": "rose",
        "subjects": {
            "General Science": ["Physics", "Chemistry", "Biology", "Science & Tech in Daily Life"],
            "Current Events": ["Tamil Nadu Events", "National Events", "Sports", "Awards", "Government Schemes"],
            "Geography": ["Tamil Nadu Geography", "India Geography", "Environment"],
            "History & Culture": ["Tamil History", "Sangam Literature", "Freedom Movement", "Tamil Nadu Culture"],
            "Polity": ["Indian Constitution", "Tamil Nadu Governance", "District Administration"],
            "Economy": ["Tamil Nadu Economy", "Agriculture", "Employment Schemes"],
            "Aptitude": ["Basic Arithmetic", "Logical Reasoning", "Number Series", "Coding-Decoding"],
        },
    },
    "TNPSC_GROUP4": {
        "name": "TNPSC Group 4",
        "short": "TNPSC-IV",
        "description": "Village Administrative Officer, Typist (Tamil Nadu)",
        "level": "state",
        "state": "Tamil Nadu",
        "languages": ["tamil", "english"],
        "color": "rose",
        "subjects": {
            "General Science": ["Basic Physics", "Basic Chemistry", "Basic Biology", "Health & Hygiene"],
            "Current Events": ["Tamil Nadu News", "National News", "Sports", "Awards"],
            "Geography": ["Tamil Nadu Districts", "Indian Geography Basics"],
            "History": ["Tamil Nadu History", "Freedom Movement Basics"],
            "Polity": ["Constitution Basics", "Local Body Administration"],
            "Aptitude": ["Arithmetic", "Logical Reasoning", "Tamil Grammar Basics"],
        },
    },
    "TNTET": {
        "name": "TNTET (Teacher Eligibility Test)",
        "short": "TNTET",
        "description": "Tamil Nadu Teacher Eligibility Test (Paper I & II)",
        "level": "state",
        "state": "Tamil Nadu",
        "languages": ["tamil", "english"],
        "color": "amber",
        "subjects": {
            "Child Development & Pedagogy": ["Child Development Theories", "Learning & Cognition", "Inclusive Education", "Assessment & Evaluation"],
            "Tamil Language": ["Tamil Grammar", "Tamil Literature", "Comprehension", "Pedagogy of Tamil"],
            "English Language": ["Grammar", "Comprehension", "Pedagogy of English"],
            "Mathematics": ["Number System", "Geometry", "Measurement", "Data Handling", "Pedagogical Issues"],
            "Environmental Studies": ["Family & Friends", "Food & Shelter", "Water & Travel", "Nature & Environment", "Pedagogy of EVS"],
        },
    },

    # ── HINDI BELT STATE EXAMS ────────────────────────────────────────
    "UPPSC": {
        "name": "UPPSC (UP Civil Services)",
        "short": "UPPSC",
        "description": "Uttar Pradesh Public Service Commission",
        "level": "state",
        "state": "Uttar Pradesh",
        "languages": ["hindi", "english"],
        "color": "yellow",
        "subjects": {
            "General Studies": ["History of UP", "UP Geography", "UP Economy", "UP Polity & Administration", "Current Affairs UP"],
            "Indian History": ["Ancient India", "Medieval India", "Modern India", "Freedom Movement"],
            "Indian Geography": ["Physical Geography", "Indian Geography", "Resources & Agriculture"],
            "Indian Polity": ["Constitution", "Parliament", "State Government", "Local Bodies"],
            "Indian Economy": ["Economic Development", "Agriculture", "Industry", "Budget & Planning"],
            "General Science": ["Physics", "Chemistry", "Biology", "Environment"],
            "Aptitude": ["Arithmetic", "Reasoning", "Data Interpretation"],
        },
    },
    "BPSC": {
        "name": "BPSC (Bihar Civil Services)",
        "short": "BPSC",
        "description": "Bihar Public Service Commission",
        "level": "state",
        "state": "Bihar",
        "languages": ["hindi", "english"],
        "color": "yellow",
        "subjects": {
            "General Studies": ["Bihar History", "Bihar Geography", "Bihar Economy", "Bihar Administration", "Current Affairs Bihar"],
            "Indian History": ["Ancient Bihar (Magadha, Patliputra)", "Medieval India", "Modern India", "Freedom Movement"],
            "Indian Geography": ["Indian Geography", "Bihar Geography", "Environment"],
            "Indian Polity": ["Constitution", "Parliament", "Bihar Government"],
            "Indian Economy": ["Economic Development", "Agriculture in Bihar", "Industry"],
            "General Science": ["Physics", "Chemistry", "Biology"],
            "Aptitude": ["Arithmetic", "Reasoning", "Data Interpretation"],
        },
    },
    "MPPSC": {
        "name": "MPPSC (MP Civil Services)",
        "short": "MPPSC",
        "description": "Madhya Pradesh Public Service Commission",
        "level": "state",
        "state": "Madhya Pradesh",
        "languages": ["hindi", "english"],
        "color": "yellow",
        "subjects": {
            "General Studies": ["MP History & Culture", "MP Geography", "MP Economy", "MP Administration", "Current Affairs MP"],
            "Indian History": ["Ancient India", "Medieval India", "Modern India", "MP's Role in Freedom Movement"],
            "Indian Geography": ["Physical Geography", "Indian Geography", "MP Geography"],
            "Indian Polity": ["Constitution", "Parliament", "MP Government"],
            "Indian Economy": ["Economic Development", "Agriculture", "Industry in MP"],
            "General Science": ["Physics", "Chemistry", "Biology", "Environment"],
            "Aptitude": ["Arithmetic", "Reasoning", "Data Interpretation"],
        },
    },
    "RPSC": {
        "name": "RPSC (Rajasthan Civil Services)",
        "short": "RPSC",
        "description": "Rajasthan Public Service Commission",
        "level": "state",
        "state": "Rajasthan",
        "languages": ["hindi", "english"],
        "color": "yellow",
        "subjects": {
            "General Studies": ["Rajasthan History & Culture", "Rajasthan Geography", "Rajasthan Economy", "Rajasthan Administration", "Current Affairs Rajasthan"],
            "Indian History": ["Ancient India", "Medieval India", "Rajput Period", "Modern India"],
            "Indian Geography": ["Physical Geography", "Rajasthan Geography", "Environment"],
            "Indian Polity": ["Constitution", "Parliament", "Rajasthan Government"],
            "Indian Economy": ["Economic Development", "Agriculture in Rajasthan", "Tourism"],
            "General Science": ["Physics", "Chemistry", "Biology"],
            "Aptitude": ["Arithmetic", "Reasoning", "Data Interpretation"],
        },
    },
}

LANGUAGE_NAMES = {
    "english": "English",
    "tamil": "தமிழ்",
    "hindi": "हिन्दी",
}

DIFFICULTY_LABELS = {
    1: "Beginner",
    2: "Easy",
    3: "Medium",
    4: "Hard",
    5: "Expert",
}

STATE_LIST = sorted(set(
    v["state"] for v in EXAM_CONTENT.values() if v["state"]
))
